### ISSUE TITLE
RC- compilation and Simulation ENV 

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/riscv-multi-core-lotr#10]
Please download / Use the Lab ENV for compiling simulating.
I expect you to have a working TB with a rtl module that has 3 component:

1) clk.   
2) reset.  
3) FlipFlop.  

you can connect the flipflop to any data you want - (counter, shirt register etc.)

compile & Simulate a test with "waives" we can examine.

**Comment by amichai-bd** [comment]
I spoke to Goel and he said you may be able to use git in the labs server - let me know if it worked.

**Comment by tzahiperetz** [comment]
closing -working good

**Comment by amichai-bd** [comment]
What compilation/simulation tool are you using?

**Comment by tzahiperetz** [comment]
synopsys tools
