### ISSUE TITLE
GPC_4T - Enable Alive Test - Basic ALU Operations

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/riscv-multi-core-lotr#16]
Enable Alive Test - Basic ALU Operations
- [x] Add/Sub/Shift Imm/Register
- [x] Jump/branch
- [x] Write results to MMIO
- [x] Test Self-Check -> if the MMIO DATA is as Expected Write to MMIO_Succesful Bit.

**Comment by adlv888** [comment]
great news!! LW,SW,ADD,ADDI,JAL tested successfully! few bugs fixed in core related to core
d_mem artificially added the size of stack pointer 288 in order to access addresses. updates on Wednesday

**Comment by amichai-bd** [comment]
![image](https://user-images.githubusercontent.com/81047407/117868292-19122e00-b2a2-11eb-89a1-0a11fb06f3c3.png)
i see what you did - but I don understand.
you added an offset for each write - and you added an offset for each read.
i don't understand what affect they have - just an offset in memory.

**Comment by adlv888** [comment]
I will explain tomorrow. in brief : the address input had the value "-266". it is illegal index for "next mem". without it its not working.
its temporary only to check . we will discuss tomorrow

**Comment by amichai-bd** [comment]
@SaarKadosh 
Please push to origin the Alive test you work on.
- alive.c   
- alive.c.s    
- alive.elf   
- alive_lef.txt   
And you may remove the old test

**Comment by SaarKadosh** [comment]
Was done and not closed.
