### ISSUE TITLE
LOTR - Getting Started

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/riscv-multi-core-lotr#163]
1. read the RC documentation and CODE review.
2. Try to compile the LOTR Design - clean compile errors
vlog.exe +define+HPATH=Alive_Mul_Core -f ../source/lotr/lotr_list.f

**Comment by adlv888** [comment]
added ps script to compile the design
no significant compilation errors

**Comment by amichai-bd** [comment]
Did you Push the fix to master branch?
