### ISSUE TITLE
LOTR - Add Tracker file for a single RC

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/riscv-multi-core-lotr#166]
To ease debugging, Please make a tracker for each RC:
single file for each RC.
should track all 8 Interfaces!! (Channel, Opcode, Address, Requestor, Data)
1. RingReqIn
2. RingRspIn
3. RingReqOut
4. RingRspOut
5. C2F_Req
6. C2F_Rsp
7. F2C_Req
8. F2C_Rsp

**Comment by adlv888** [comment]
ok so this one i did

**Comment by amichai-bd** [comment]
@adlv888 - reminder, Please send a screenshot here & close this issue.

**Comment by adlv888** [comment]
![image](https://user-images.githubusercontent.com/81635109/166161969-5c809366-12ef-49d6-b9ff-4a2bb394d497.png)

**Comment by adlv888** [comment]
not closing yet, adding some fixes we talked about (like ---- on read "requested data")

**Comment by adlv888** [comment]
![image](https://user-images.githubusercontent.com/81635109/169650220-97b624a7-801e-4184-bdfe-4c5a307ba99c.png)
