### ISSUE TITLE
LOTR - RC debug

### ISSUE THREAD

**Issue by adlv888** [amichai-bd/riscv-multi-core-lotr#172]
![image](https://user-images.githubusercontent.com/81635109/162138038-3413a41e-1c52-4030-a38e-cb0f2b156846.png)
seems that RC is having some issues with transactions
need to debug

**Comment by adlv888** [comment]
found the issue with the READ. ridiculous and amazing issue :
![image](https://user-images.githubusercontent.com/81635109/166161336-63cd969f-547d-47f7-a7c5-b6afcf2a190d.png)

"d_mem" had no signal called "pre_q_b". only the assign with no declaration. I added this declaration and it fixed(Line 39):
![image](https://user-images.githubusercontent.com/81635109/166161368-b66e0539-e128-4e41-aee5-c2fe6b45389c.png)

 how is this possible ? how it was compiled until now ? WTF?!

**Comment by amichai-bd** [comment]
We should start running more advanced "Static checks" that make sure we dont have this kind of issue again.
A good option is to use the "quartos compiler" - this will notify us in case we have any other similar violations.
