### ISSUE TITLE
LOTR.inc- Enable UART Tile phase 1

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/riscv-multi-core-lotr#193]
## Phase 1:
- Create UART Tile (instantiate an RC module in it)
- Add a Shift register to accept all the UART Transaction
- Design a State machine to consume the Register & packet it to an RC transaction.

**Comment by ChrisShakkour** [comment]
initial UART rtl design IP committed, to develop a uart State machine for configuring and managing the gateway between the ring interface and the outer Uart Host.

**Comment by ChrisShakkour** [comment]
Tile created. on STUB design (Black box)

**Comment by ChrisShakkour** [comment]
Resolved - migrated to other small tasks.
