### ISSUE TITLE
LOTR - The Documentation 

### ISSUE THREAD

**Issue by adlv888** [amichai-bd/riscv-multi-core-lotr#195]

**Comment by amichai-bd** [comment]
מבחינת דוקומנטציה, אני לא מחפש משהו ארוך במיוחד. אלו הנקודות העיקריות:
1) הסבר על VA vs PA (זיכרון פיסיקלי לעומת וורטואלי) ברמת הcore וברמת הSOC.
2) הסבר על הRING והTILE
3) הסבר על הVGA  החומרה והפרוטוקול.
4) הסבר על הDE10Lite
5) הסבר על הCR החדשים של הDE10LIte.
6) הפרמטרים האפשריים של הפרוייקט (מספר cores וגודל זכרונות)
7) דוגמאות קוד לsingle threads, 4 THreads ו8 THreads.87 + ספריות תוכנה בסיסיות + צילומי מסך ופלטים.
8) עולם הוולאדיציה והוורפיקציה של התוכנה + חומרה + FPGA + סימוציה
9) פרק קצר על כלים, סקריפטים, גיט, סביבה פיתוח וכו.
