### ISSUE TITLE
LOTR - make a 4 thread test with VGA feedback

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/riscv-multi-core-lotr#201]
To avoid problems in the ring. Make a test with a single-core - 4 threads.

Split the Display to 4 squares. Each will be written from a different thread.

Rectangles are generated by writing 0xFFFFFFFF to a specific VGA address offset.
1) counter - represented by a number of rectangles.
2) rotating rectangle around the perimeter
3) simple patterns switching (checkers, lines, etc.)
4) spell hello using rectangles

**Comment by amichai-bd** [comment]
Please program this:
https://www.youtube.com/watch?v=ZZuD6iUe3Pc

**Comment by adlv888** [comment]
![image](https://user-images.githubusercontent.com/81635109/183263476-5b5bca84-7294-4d99-a073-70bd85a8d8ec.png)

**Comment by amichai-bd** [comment]
The example you made looks great!
![image](https://user-images.githubusercontent.com/81047407/185355670-2295fb21-fb8f-4add-b22a-0de8d7f27e7b.png)

But I think it's still missing a header per thread:
- "Thread 0 - Bubble Sort"
- "Thread 1 - Quick Sort"
- etc.
