### ISSUE TITLE
GPC_4T - break down the Instruction at Q102 and not Q101 - will save  many FF 

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/riscv-multi-core-lotr#22]
Looking at the diagram (and the code) we can see that Many of the samples at 101->102 are just different bits of the Instruction.  
![image](https://user-images.githubusercontent.com/81047407/115982451-d400b300-a5a3-11eb-8e58-24d12b936970.png)  

We should sample the "raw" Instruction 101->102 and at 102 we will break down the bits into the relevant structures:   
- Immediate B/J/U/I/S.  
- RegWrPtr
- Funct7
- Funct3  

This will save many redundant FF - and as far as I can tell won't affect the Tpd timing in Cycle 102.  
Let me know what you guys think.

**Comment by adlv888** [comment]
with this implementation the decode stage will spread on 2 pipe stages 101 102 and can be little confusing. I personally prefer order but I will consult with Saar.

**Comment by adlv888** [comment]
accept both ABD and SK opinion. Done
