### ISSUE TITLE
LOTR - make a 8  thread: 2 types of sorting, 4 Data Sets.

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/riscv-multi-core-lotr#220]
https://www.toptal.com/developers/sorting-algorithms
**2 Algorithm**
- Bubble Sort
- insertionSort / quickSortIterative / mergeSort
**4 Data Sets:**
- random
- few unique
- reversed
- almost sorted

8 in total Threads. (4x2)

**Comment by adlv888** [comment]
![image](https://user-images.githubusercontent.com/81635109/188510422-aa800701-3df0-44df-b60d-ea2ec76aa965.png)

clockwise from top left : random, reverse, few unique, almost sorted.
 
insertion above bubble
