### ISSUE TITLE
GPC_4T - arch bug with Store and more

### ISSUE THREAD

**Issue by adlv888** [amichai-bd/riscv-multi-core-lotr#32]
![image](https://user-images.githubusercontent.com/81635109/117834880-32a27e00-b280-11eb-9460-a64323e0f631.png)

I think it should be "RegRdData2Q102"

in this implementation we add the immediate with address at "RegRdData**1**Q102" and store "RegRdData**1**Q102" in this
it should be "RegRdData2Q102"

**Comment by amichai-bd** [comment]
I agree.
Good find!

Was this only in the documentation or also in code?

**Comment by adlv888** [comment]
in code also
