### ISSUE TITLE
SW ARCH - Write a simple multi-thread program to run on a single core (4 threads).

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/riscv-multi-core-lotr#33]
Write a simple multi-thread program to run on a single core (4 threads).
- [x] Define Basic CR you need - Must use the thread_id CR.  May use other CRs you define.
- [x] Design SW communication protocol handshake to move data between threads. - busy waits and poling / synchronize etc.
- [x] Document the memory space allocation and the "regions/memory layout". ( thread0/1/2/3 local storage(stack pointer offset),  shared memory region, CRs needed, etc..)

**Comment by amichai-bd** [comment]
@DL8

**Comment by DL8** [comment]
Library is implemented with two example applications: empty (no content, just library loading everything) and prime factoring. I put ebreaks in the initialization part because it's still an architectural open, but once we resolve it I can fix and let it run
