### ISSUE TITLE
Use libgcc implementation for multiplication and division in library

### ISSUE THREAD

**Issue by DL8** [amichai-bd/riscv-multi-core-lotr#58]
Current library has a custom implementation uses custom implementation for arithmetic operations (multiplication in entry point, modulus in prime factoring). It may be more flexible to use libgcc implementation, so it will be placed automagically if built without M extension.

Possible challenges:
1. Currently entry point code is linked as a separate object file (instead of a proper static library, like the rest of the library). Need to build it such that the multiplication will be done properly
2. Need to make sure that gcc doesn't add too much garbage into the binary

**Comment by amichai-bd** [comment]
from my experience, gcc will add only the rutines needed for your code.
Meaning, if you have only "multiplier"  and not dividers in your code, 
the gcc will link only the "mulsi" routine - and not the "div" routine.
So gcc doesn't add much garbage.
