### ISSUE TITLE
GPC_4T - Heap enabling

### ISSUE THREAD

**Issue by adlv888** [amichai-bd/riscv-multi-core-lotr#61]
how to generate the Systemverilog heap data so we can "load" it with the test

**Comment by DL8** [comment]
I think the linker script should create a data segment, such that the data section will be in D_MEM. I don't know how to distinguish between global and local data with this approach though.

Yesterday in the library I added compilation-defined memory layout and the next step is to make it create a linker script that initializes memory according to the memory layout (e.g. place global variables in global data and in the future local data in local data sections)

**Comment by adlv888** [comment]
after discussion , 2 issues regarding this:
1. the "HEAP" is  defined in this address:
![image](https://user-images.githubusercontent.com/81635109/129727027-314953f4-f615-4050-a771-0b84d6c4c852.png)
all 4 threads takes data from this address which belong to certain thread and copy to seperate registers which is little wierd:
![image](https://user-images.githubusercontent.com/81635109/129727394-a401dcae-e1e4-49b8-996a-cb518807204a.png)
in this there is a 10 sized array.

2.bigger issue is with bigger arrays. in a 20 sized array the assembly code uses "memcpy" function which doesn't work and d_mem is empty besides the heap:
![image](https://user-images.githubusercontent.com/81635109/129727716-ed9aaeec-d4ca-410d-97ef-5eb684c0da84.png)

**Comment by adlv888** [comment]
correction for 2 - it works and write to memory but after few cycles it overwrite the data with "xxxxxxxx"

**Comment by adlv888** [comment]
we want the "HEAP" to be on shared mem?

**Comment by amichai-bd** [comment]
I think we want this region of memory to be loaded to a shared dedicated area - should not be reliteive to the Stack Pointer offset.
All threads can access this area and modify this data independently - In SW you need to make sure they use this data in a coherent way - so they won't override each others modifications.

**Comment by amichai-bd** [comment]
I agree we might have a problem here - if each thread will allocate parts of this area independently they might override each other.
We should talk about what's going on in the data_mem allocation when you set arrays within the "Main" vs in the specific thread.

**Comment by adlv888** [comment]
![image](https://user-images.githubusercontent.com/81635109/130599588-74274fbd-f68b-450d-81cf-459a427b93bc.png)
Heap worked with a lot of data. closing issue
