### ISSUE TITLE
GPC_4T - EBREAK ECALL enabling

### ISSUE THREAD

**Issue by adlv888** [amichai-bd/riscv-multi-core-lotr#75]
support these 2 opcodes on t.b

**Comment by DL8** [comment]
Note that architecturally these instructions generate exception ("Environment call from M-mode" in case of ECALL (this will change if privilege levels are supported) and "Breakpoint" in case of EBREAK). In my vision, when encountered the testbench should invoke some hooks to perform special functions (e.g. compare the results of a test)
