### ISSUE TITLE
GPC_4T - crt0 enhancement

### ISSUE THREAD

**Issue by adlv888** [amichai-bd/riscv-multi-core-lotr#76]
crt0 enhancement

**Comment by DL8** [comment]
I've already implemented entry point code (crt0) in the library. Why don't you use it?

**Comment by amichai-bd** [comment]
For now, I think it's good that they use the code they wrote themself.
It may be missing features and possible solutions to problems they will encounter later.
The simple crt0 they are using now is what i asked them to use.
