### ISSUE TITLE
GPC_4T - Division Test

### ISSUE THREAD

**Issue by adlv888** [amichai-bd/riscv-multi-core-lotr#87]
Division operation that is not between integers that are power of two, seem to not work
need to debug it

**Comment by adlv888** [comment]
![image](https://user-images.githubusercontent.com/81635109/123562158-8aa42e00-d7b5-11eb-8f59-a15f1094a0c1.png)
ARGGGGGHHHHHH!~!~!!!!!! Nailed it

**Comment by amichai-bd** [comment]
Fixed
