### ISSUE TITLE
GPC_4T - execute 4 threaded simple calculations program

### ISSUE THREAD

**Issue by adlv888** [amichai-bd/riscv-multi-core-lotr#95]
compile & simulate a  simple program that simultaneously execute  4 different calculations

![image](https://user-images.githubusercontent.com/81635109/122954050-c9864e00-d387-11eb-9b18-7ad7efc2da98.png)

**Comment by adlv888** [comment]
![image](https://user-images.githubusercontent.com/81635109/122954225-ede22a80-d387-11eb-9b6d-e9de062af446.png)
so cool

**Comment by amichai-bd** [comment]
Good job - This is great!
It would be even cooler to make them work together to calculate together to accelerate calculation time.
Like a distributed Computation of a prime factor of a number. (each thread will search for prime factors within a Range(

**Comment by DL8** [comment]
Could the Sieve of Eratosthenes can be an interesting example for that? In its basic approach I feel it can be executed concurrently, but the naive approach may lead to some redundant work

https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes
