### ISSUE TITLE
SUPPORTED_ARCH CR was removed from SW-HW interface documentation

### ISSUE THREAD

**Issue by DL8** [amichai-bd/riscv-multi-core-lotr#97]
SUPPORTED_ARCH CR (offset 0xc) was removed from SW-HW interface and was replaced with another CR. I believe that was a mistake. It doesn't have to be at the same index, but I believe it should remain

**Comment by amichai-bd** [comment]
not sure what you mean.
![image](https://user-images.githubusercontent.com/81047407/122989555-9eadf100-d3ab-11eb-998c-d7fa6b515208.png)
I see here the offset 0xC is defined as MY_STACK_BASE_OFFSET.
Is that wrong?

**Comment by DL8** [comment]
Comparing the page's history with your latest change:
![image](https://user-images.githubusercontent.com/3604408/122993142-a2dc0d80-d3af-11eb-898b-47c86420d83c.png)
